import { lazy, Suspense, useEffect, useState } from 'react';
import { Plus, Save, Download, FolderOpen, Image, Box, Settings2 } from 'lucide-react';
import { equipment, getEquipment } from '../data/catalog.js';
import { saveEquipment, uploadAsset, validateEquipment, libraryStatus } from '../lib/library.js';
import { downloadFile } from '../lib/storage.js';
import { PageHeading, localPath } from './UI.jsx';
import { PictureSource } from './EquipmentPicture.jsx';
import { replacePicture } from '../lib/equipmentPictures.js';
import '../builder.css';
const ModelScene=lazy(()=>import('./ModelScene.jsx'));
const emptyItem=()=>({id:'',name:'',model:'',category:'',location:'',status:'Needs verification',role:'',specs:[],url:'',alternatives:'',note:'',image:'',model3d:'',modelReference:'',dimensions:''});
export default function Admin({onSaved}) {
  const [item,setItem]=useState(()=>structuredClone(equipment[0])),[isNew,setIsNew]=useState(false),[status,setStatus]=useState(null),[notice,setNotice]=useState(''),[busy,setBusy]=useState(false),[preview,setPreview]=useState('image'),[cadAxis,setCadAxis]=useState('y');
  useEffect(()=>{libraryStatus().then(setStatus);},[]);
  const writable=!!status?.writable;
  function patch(key,value) {setItem(i=>key==='image'?replacePicture(i,value):({...i,[key]:value}));setNotice('');}
  async function save(event) {event.preventDefault();setBusy(true);try{validateEquipment(item);if(isNew&&getEquipment(item.id))throw new Error('That equipment ID already exists. Choose a different ID.');await saveEquipment(item);setIsNew(false);onSaved();setNotice('Saved to public/library/equipment.json. Changes are now available throughout the app.');}catch(error){setNotice(error.message);}finally{setBusy(false);}}
  async function upload(event,kind) {const file=event.target.files[0];event.target.value='';if(!file)return;setBusy(true);try{if(!/^[a-z0-9][a-z0-9-]{0,79}$/.test(item.id))throw new Error('Set a valid equipment ID before attaching assets.');const asset=await uploadAsset(file,kind,item.id,cadAxis);if(kind==='step'){setItem(i=>({...i,stepPath:asset.path,stepSha256:asset.stepSha256,model3d:asset.model3d,cadKind:'User-provided CAD',cadReview:'Uploaded STEP converted locally. Confirm source, units, mounting and orientation.',modelReference:'Uploaded STEP: '+asset.path+'; browser GLB: '+asset.model3d}));setPreview('model');}else patch(kind==='images'?'image':'model3d',asset);setNotice('File stored in the project folder. Save equipment to link it to the library.');}catch(error){setNotice(error.message);}finally{setBusy(false);}}
  return <><PageHeading title="Admin" action={<button className="button secondary" onClick={()=>{setItem(emptyItem());setIsNew(true);setNotice('New equipment draft.');}}><Plus size={16}/>Add equipment</button>}>Maintain the shared equipment catalog, pictures and detailed 3D model references.</PageHeading><div className={`admin-storage panel ${writable?'connected':''}`}><FolderOpen size={23}/><div><strong>{writable?'Connected to local project library':'Catalog export mode'}</strong><p>{writable?status.folder:'Open http://localhost:5174 on the development computer to save directly to the project folder. On GitHub Pages, export your changes and commit the library files.'}</p></div><span>{writable?'Local file editing':'No file writes'}</span></div>
    {notice&&<div className="builder-notice" role="status">{notice}</div>}
    <div className="admin-layout"><aside className="panel admin-list"><div className="rail-heading">Library records <span>{equipment.length}</span></div>{equipment.map(e=><button className={`inventory-item ${!isNew&&item.id===e.id?'selected':''}`} key={e.id} onClick={()=>{setItem(structuredClone(e));setIsNew(false);setNotice('');}}><div><strong>{e.name}</strong><small>{e.model}</small></div><Settings2 size={15}/></button>)}</aside>
    <form className="panel admin-form" onSubmit={save}><div className="section-heading"><div><h3>{isNew?'New equipment':'Edit equipment'}</h3><p>Stable IDs keep equipment references intact.</p></div><button className="button primary" type="submit" disabled={busy||!writable}><Save size={15}/>{busy?'Working…':'Save to library'}</button></div><div className="admin-fields">{[['id','Equipment ID'],['name','Equipment name'],['model','Manufacturer / model'],['category','Category'],['location','Lab / location'],['status','Documentation status'],['url','Manufacturer website'],['dimensions','Physical dimensions / units']].map(([key,label])=><label key={key}>{label}{key==='status'?<select value={item[key]} onChange={e=>patch(key,e.target.value)}>{['Documented','Service listed','Needs verification','Planned','In development'].map(s=><option key={s}>{s}</option>)}</select>:<input value={item[key]||''} required={['id','name','model','category'].includes(key)} disabled={key==='id'&&!isNew} onChange={e=>patch(key,e.target.value)}/>}</label>)}</div><label className="admin-wide">Purpose / role<textarea rows={2} value={item.role} onChange={e=>patch('role',e.target.value)}/></label><div className="spec-editor"><div><h3>Specifications</h3><button type="button" className="text-button" onClick={()=>patch('specs',[...item.specs,['','']])}><Plus size={14}/>Add specification</button></div>{item.specs.map(([key,value],i)=><div className="spec-editor-row" key={i}><input aria-label={`Specification ${i+1} label`} placeholder="Parameter" value={key} onChange={e=>patch('specs',item.specs.map((r,j)=>i===j?[e.target.value,r[1]]:r))}/><input aria-label={`Specification ${i+1} value`} placeholder="Value / units" value={value} onChange={e=>patch('specs',item.specs.map((r,j)=>i===j?[r[0],e.target.value]:r))}/><button type="button" className="icon-button" aria-label={`Remove specification ${i+1}`} onClick={()=>patch('specs',item.specs.filter((_,j)=>i!==j))}>×</button></div>)}</div>{[['alternatives','Alternatives & compatibility'],['note','Evidence / verification notes'],['modelReference','Model source, licence and reference files'],['cadKind','CAD type (Vendor CAD / Illustrative reference)'],['cadReview','Model accuracy and review notes'],['cadSource','CAD source / supplier link']].map(([key,label])=><label className="admin-wide" key={key}>{label}<textarea rows={2} value={item[key]||''} onChange={e=>patch(key,e.target.value)}/></label>)}<div className="admin-export"><button type="button" className="button secondary" onClick={()=>{try{validateEquipment(item);downloadFile('equipment.json',{version:1,equipment:equipment.filter(e=>e.id!==item.id).concat(item)});setNotice('Catalog exported. Replace public/library/equipment.json with this file when preparing the repository.');}catch(error){setNotice(error.message);}}}><Download size={15}/>Export catalog with draft</button><p>Unsaved form changes stay in this draft until you save or export.</p></div></form>
    <aside className="panel admin-assets"><div className="rail-heading">Picture & model</div><div className="builder-view-tabs"><button className={preview==='image'?'active':''} onClick={()=>setPreview('image')}><Image size={16}/>Picture</button><button className={preview==='model'?'active':''} onClick={()=>setPreview('model')}><Box size={16}/>3D model</button></div>{preview==='image'?<div className="admin-picture">{item.image?<img src={localPath(item.image)} alt={`${item.name} reference`}/>:<div><Image size={32}/><p>No equipment picture attached</p></div>}</div>:item.model3d?<Suspense fallback={<p>Loading model viewer…</p>}><ModelScene items={[item]} nodes={[{id:'preview',equipmentId:item.id,x:440,y:255}]} /></Suspense>:<div className="admin-picture"><div><Box size={35}/><p>Detailed model awaiting reference files</p></div></div>}
    <div className="builder-fields">{preview==='image'&&<PictureSource item={item}/>}<label>Picture path<input value={item.image||''} placeholder="library/images/equipment.jpg" onChange={e=>patch('image',e.target.value)}/></label><label className="asset-upload">Attach picture<input type="file" accept=".png,.jpg,.jpeg,.webp" disabled={!writable||busy} onChange={e=>upload(e,'images')}/></label>{[['imageSource','Picture source website'],['imageCredit','Picture credit / owner'],['imageKind','Picture type (product / assembly / reference / lab context)'],['imageModel','Equipment shown in picture'],['imageReview','Picture accuracy / review notes'],['imageRights','Picture copyright / licence notes']].map(([key,label])=><label key={key}>{label}<input value={item[key]||''} onChange={e=>patch(key,e.target.value)}/></label>)}<label>Model path<input value={item.model3d||''} placeholder="library/models/equipment.glb" onChange={e=>patch('model3d',e.target.value)}/></label><label className="asset-upload">Attach GLB model<input type="file" accept=".glb" disabled={!writable||busy} onChange={e=>upload(e,'models')}/></label><label>STEP source up-axis<select aria-label="STEP source up-axis" value={cadAxis} onChange={e=>setCadAxis(e.target.value)}><option value="y">Y-up (keep source axes)</option><option value="z">Z-up (rotate to viewer Y-up)</option></select></label><label className="asset-upload">Attach STEP / STP and convert<input type="file" accept=".step,.stp" disabled={!writable||busy||!status?.cadConversion} onChange={e=>upload(e,'step')}/></label><p className="builder-help">{status?.cadConversion?'Local CAD converter connected. STEP files are retained and converted to GLB; save equipment to link both files. Confirm orientation in the preview.':'STEP conversion needs the local OpenCascade tool. Keep source CAD and attach a GLB if conversion is unavailable.'}</p><label>Original STEP path<input value={item.stepPath||''} placeholder="library/references/equipment/model.step" onChange={e=>patch('stepPath',e.target.value)}/></label>{item.stepPath&&<a className="button secondary" href={localPath(item.stepPath)} download>Download STEP for SolidWorks</a>}{item.nativeCad?.length>0&&<div className="cad-card"><strong>Original SolidWorks source</strong><p>{item.nativeCadNote}</p>{item.nativeCad.map(c=><a key={c.path} href={localPath(c.path)} download>{c.label}</a>)}</div>}<div className="cad-card"><strong>{item.cadKind||'Model type not recorded'}</strong><p>{item.cadReview||'Record whether the model is measured, vendor-supplied or illustrative.'}</p></div><p className="builder-help">Self-contained GLB 2.0 models, up to 40 MB. Convert vendor CAD to GLB before adding it. Include textures in the file; compressed models requiring external decoders are not supported.</p><p className="builder-help">Reference photos, dimension drawings and original CAD can be placed in <code>public/library/references/</code>. Record their source and licence above.</p></div></aside></div></>;
}

