import { lazy, Suspense, useState, useMemo } from 'react';
import { Cpu, MapPin, Download, ArrowRight, Box, Image } from 'lucide-react';
import { equipment, getEquipment, setups } from '../data/catalog.js';
import { PageHeading, SearchBox, Status, Empty, External, localPath } from './UI.jsx';
import { downloadFile } from '../lib/storage.js';
import { EquipmentPicture, PictureSource } from './EquipmentPicture.jsx';
import '../builder.css';
const ModelScene=lazy(()=>import('./ModelScene.jsx'));

export function EquipmentDetail({ item }) {
  const [media,setMedia]=useState('3d');
  const modelNodes=useMemo(()=>[{id:'model',equipmentId:item.id,x:440,y:255}],[item.id]);
  return <div className="equipment-detail"><div className="detail-title"><div className="equipment-symbol"><Cpu size={28}/></div><div><h2>{item.name}</h2><p>{item.model}</p></div></div><Status value={item.status}/><div className="equipment-media"><div className="equipment-media-tabs" role="tablist" aria-label="Equipment media"><button role="tab" aria-selected={media==='3d'} onClick={()=>setMedia('3d')}><Box size={16}/>3D model</button><button role="tab" aria-selected={media==='picture'} onClick={()=>setMedia('picture')}><Image size={16}/>Picture</button></div><div className="equipment-media-window" role="tabpanel" aria-label={media==='3d'?'Equipment 3D model':'Equipment picture'}>{media==='3d'?(item.model3d?<Suspense fallback={<div className="model-stage model-loading">Loading model…</div>}><ModelScene key={item.id} items={[item]} nodes={modelNodes}/></Suspense>:<div className="equipment-media-empty"><Box size={32}/><p>No 3D model added yet.</p><small>Add a STEP or GLB model in Admin.</small></div>):<EquipmentPicture key={item.image} item={item}/>}</div>{media==='picture'&&<PictureSource item={item}/>}</div>{item.stepPath&&<div className="cad-card equipment-cad-note"><strong>{item.cadKind||'CAD reference'}</strong><p>{item.cadReview}</p><a href={localPath(item.stepPath)} download>Download STEP for SolidWorks</a></div>}{item.nativeCad?.length>0&&<div className="cad-card equipment-cad-note"><strong>Original SolidWorks source</strong><p>{item.nativeCadNote}</p>{item.nativeCad.map(c=><a key={c.path} href={localPath(c.path)} download>{c.label}</a>)}</div>}<p className="detail-role">{item.role}</p><dl className="spec-list">{item.specs.map(([label,value]) => <div key={label}><dt>{label}</dt><dd>{value}</dd></div>)}</dl><h3>Alternatives & compatibility</h3><p>{item.alternatives}</p><div className="note">{item.note}</div>{item.url && <External href={item.url} className="button secondary">Manufacturer / source</External>}</div>;
}

export function SetupEquipment({ setup, onInspect }) {
  return <div className="tab-content"><div className="section-heading"><div><h3>Equipment in this setup</h3><p>Documented components and items awaiting local verification.</p></div></div>{setup.id.startsWith('wafer') && <div className="note">The WST instrument models require verification. The chip setup’s Keysight module models are not confirmed for the wafer platform.</div>}<div className="equipment-rows">{setup.equipment.map(id => {const item=getEquipment(id);return <button className="equipment-row" key={id} onClick={() => onInspect(id)}><div className="equipment-symbol"><Cpu size={21}/></div><div><strong>{item.name}</strong><small>{item.model}</small></div><Status value={item.status}/><ArrowRight size={18}/></button>;})}</div></div>;
}

export default function EquipmentLibrary({ initialId, onExplore }) {
  const [query, setQuery] = useState('');
  const [category, setCategory] = useState('');
  const [selected, setSelected] = useState(initialId || 'laser');
  const filtered = equipment.filter(e => (!category || e.category === category) && `${e.id} ${e.name} ${e.model} ${e.location}`.toLowerCase().includes(query.toLowerCase()));
  const item = getEquipment(selected) || equipment[0];
  return <><PageHeading title="Equipment library" action={<button className="button secondary" onClick={() => downloadFile('cornerstone-equipment.json', {version:1, asOf:new Date().toISOString().slice(0,10), equipment})}><Download size={16}/>Export catalog</button>}>Explore the lab inventory, specifications and compatible alternatives.</PageHeading><div className="library-toolbar"><SearchBox value={query} onChange={setQuery} placeholder="Search equipment, model or lab…" label="Search equipment"/><label className="inline-select"><span>Category</span><select value={category} onChange={e => setCategory(e.target.value)}><option value="">All equipment</option>{[...new Set(equipment.map(e=>e.category))].map(c=><option key={c}>{c}</option>)}</select></label></div><div className="library-layout"><div className="panel equipment-list"><div className="rail-heading">Lab inventory <span>{filtered.length} items</span></div>{filtered.map(e=><button key={e.id} className={`inventory-item ${selected===e.id?'selected':''}`} onClick={()=>setSelected(e.id)}><div><strong>{e.name}</strong><small>{e.model}</small><span className="location"><MapPin size={12}/>{e.location}</span></div><Status value={e.status}/></button>)}{!filtered.length && <Empty title="No equipment found">Try a different model, lab or category.</Empty>}<div className="rail-note">Inventory is a documentation snapshot. Serial numbers, quantities, calibration dates and booking availability have not been supplied.</div></div><div className="panel"><EquipmentDetail key={item.id} item={item}/><div className="related-setups"><h3>Used / referenced in</h3>{setups.filter(s=>s.equipment.includes(item.id)).map(s=><button className="related-link" key={s.id} onClick={()=>onExplore(s.id)}>{s.name}<ArrowRight size={14}/></button>)}</div></div></div></>;
}

