import { useEffect, useMemo, useState } from 'react';
import { Search, CheckCircle2, AlertCircle, Box, Download, Save, ArrowRight, Pencil } from 'lucide-react';
import { equipment } from '../data/catalog.js';
import { equipmentReadiness, workspaceSeed } from '../lib/workspace_draft.js';
import { validateEquipment, libraryStatus } from '../lib/library.js';
import { readLocal, writeLocal, downloadFile } from '../lib/storage.js';
import { EquipmentDetail } from './Equipment.jsx';
import '../workspaces_draft.css';

function initial(){const stored=readLocal('equipment_draft',null);if(!Array.isArray(stored?.equipment))return structuredClone(equipment);try{stored.equipment.forEach(validateEquipment);const map=new Map(equipment.map(e=>[e.id,e]));stored.equipment.forEach(e=>map.set(e.id,e));return structuredClone([...map.values()]);}catch{return structuredClone(equipment);}}
export default function Equipment_draft({onAdmin}){
  const [items,setItems]=useState(initial),[selected,setSelected]=useState('wst-polarisation-manual'),[query,setQuery]=useState(''),[filter,setFilter]=useState('all'),[category,setCategory]=useState(''),[edit,setEdit]=useState(false),[notice,setNotice]=useState(''),[storage,setStorage]=useState(null),[busy,setBusy]=useState(false);
  const item=items.find(e=>e.id===selected)||items[0];
  const setup=useMemo(()=>workspaceSeed(),[]),instance=setup.nodes.find(n=>n.equipmentId===item.id);
  const rows=items.map(e=>({item:e,checks:equipmentReadiness(e,setup.nodes.find(n=>n.equipmentId===e.id))}));
  const filtered=rows.filter(({item:e,checks})=>(!category||e.category===category)&&`${e.id} ${e.name} ${e.model}`.toLowerCase().includes(query.toLowerCase())&&(filter==='all'||filter==='model'&&!e.model3d||filter==='picture'&&!e.image||filter==='reference'&&e.cadKind!=='Vendor CAD'||filter==='details'&&checks.some(c=>!c.done)));
  const modelCount=items.filter(e=>e.model3d).length,pictureCount=items.filter(e=>e.image).length,vendorCount=items.filter(e=>e.cadKind==='Vendor CAD').length;
  useEffect(()=>{libraryStatus().then(setStorage);},[]);
  useEffect(()=>{const t=setTimeout(()=>{if(!writeLocal('equipment_draft',{version:1,workspaceName:'Equipment_draft',equipment:items}))setNotice('Browser storage unavailable. Export your draft catalog.');},350);return()=>{clearTimeout(t);writeLocal('equipment_draft',{version:1,workspaceName:'Equipment_draft',equipment:items});};},[items]);
  function patch(key,value){setItems(es=>es.map(e=>e.id===item.id?{...e,[key]:value}:e));setNotice('Equipment_draft changed · shared library unchanged.');}
  async function save(){setBusy(true);try{items.forEach(validateEquipment);const r=await fetch('/api/library/workspace-draft',{method:'PUT',headers:{'Content-Type':'application/json'},body:JSON.stringify({version:1,workspaceName:'Equipment_draft',equipment:items})});const data=await r.json();if(!r.ok)throw new Error(data.error);setNotice(`Saved separately to public/${data.path}. The shared equipment catalog is unchanged.`);}catch(e){setNotice(e.message);}finally{setBusy(false);}}
  async function load(){try{const r=await fetch(`${import.meta.env.BASE_URL}library/workspaces_draft/equipment_draft.json`,{cache:'no-store'});if(!r.ok)throw new Error('No saved equipment draft found.');const data=await r.json();if(data.workspaceName!=='Equipment_draft'||!Array.isArray(data.equipment)||!data.equipment.length)throw new Error('Invalid Equipment_draft file.');data.equipment.forEach(validateEquipment);setItems(data.equipment);setNotice('Saved Equipment_draft loaded.');}catch(e){setNotice(e.message);}}
  return <div className="draft-workspace"><div className="draft-heading"><div><span className="draft-eyebrow">CORNERSTONE / EQUIPMENT COMPLETENESS</span><h1>Equipment<span>_draft</span></h1><p>See what is documented. Find what is missing. Review equipment records.</p></div><div className="draft-heading-actions"><button className="button secondary" onClick={load}>Load local</button><button className="button secondary" onClick={()=>downloadFile('equipment_draft.json',{version:1,workspaceName:'Equipment_draft',equipment:items})}><Download size={15}/>Export draft</button><button className="button primary" disabled={!storage?.writable||busy} onClick={save}><Save size={15}/>Save draft locally</button></div></div>
    <div className="draft-metrics"><div><span>CATALOG</span><strong>{items.length}</strong><small>equipment records</small></div><div><span>3D MODELS</span><strong>{modelCount}<em>/{items.length}</em></strong><small>browser previews available</small></div><div><span>PICTURES</span><strong>{pictureCount}<em>/{items.length}</em></strong><small>reference images supplied</small></div><div><span>VENDOR CAD</span><strong>{vendorCount}</strong><small>other models need provenance review</small></div></div>
    {notice&&<div className="draft-notice" role="status">{notice}</div>}<div className="draft-equipment-toolbar"><label><Search size={16}/><input aria-label="Equipment draft search" placeholder="Search equipment, model or ID…" value={query} onChange={e=>setQuery(e.target.value)}/></label><select aria-label="Equipment draft category" value={category} onChange={e=>setCategory(e.target.value)}><option value="">All categories</option>{[...new Set(items.map(e=>e.category))].map(c=><option key={c}>{c}</option>)}</select><select aria-label="Equipment draft readiness filter" value={filter} onChange={e=>setFilter(e.target.value)}><option value="all">All records</option><option value="model">Missing 3D model</option><option value="picture">Missing picture</option><option value="reference">Illustrative / unverified CAD</option><option value="details">Missing record details</option></select></div>
    <div className="draft-equipment-layout"><div className="draft-record-list panel"><div className="draft-list-heading">{filtered.length} matching records</div>{filtered.map(({item:e,checks})=><button key={e.id} className={selected===e.id?'selected':''} onClick={()=>{setSelected(e.id);setEdit(false);}}><Box size={19}/><span><strong>{e.name}</strong><small>{e.model}</small><em>{e.id}</em><div className="draft-record-badges"><span>{e.model3d?'3D':'3D pending'}</span><span>{e.image?'Picture':'No picture'}</span></div></span><div className="draft-completion-number">{checks.filter(c=>c.done).length}<small>/{checks.length}</small></div></button>)}{!filtered.length&&<div className="draft-empty">No matching equipment. Clear a filter to see more records.</div>}</div>
    <section className="panel draft-equipment-detail"><div className="draft-equipment-review-bar"><span>Draft copy · shared catalog unchanged</span><button className="button secondary" onClick={()=>setEdit(v=>!v)}><Pencil size={14}/>{edit?'Close editing':'Edit draft record'}</button></div>
      {edit?<div className="draft-record-form"><h2>{item.name}</h2><p>Stable equipment ID: {item.id}. These edits stay in Equipment_draft.</p>{[['name','Equipment name'],['model','Model / option'],['dimensions','Dimensions and units'],['serial','Asset / serial number'],['calibration','Calibration record'],['url','Specification website'],['image','Picture path'],['model3d','GLB model path']].map(([key,label])=><label key={key}>{label}<input aria-label={`Draft equipment ${label}`} value={item[key]||''} onChange={e=>patch(key,e.target.value)}/></label>)}<label>Specifications<SpecificationsDraft key={item.id} specs={item.specs} onChange={specs=>patch('specs',specs)}/><small>One specification per line: Label: value and units.</small></label><label>Notes<textarea rows={3} value={item.note} onChange={e=>patch('note',e.target.value)}/></label></div>:<EquipmentDetail key={item.id} item={item}/>}
      <div className="draft-record-checklist"><h3>Documentation checklist</h3><p>Coverage indicates recorded information, not calibration validity or measurement approval.</p><ul className="draft-readiness-list">{equipmentReadiness(item,instance).map(c=><li key={c.label}>{c.done?<CheckCircle2 size={16}/>:<AlertCircle size={16}/>}<span>{c.label}</span><small>{c.done?'Recorded':'Missing'}</small></li>)}</ul><button className="button secondary" onClick={onAdmin}>Open shared Admin for asset uploads<ArrowRight size={14}/></button></div>
    </section></div>
  </div>;
}

function SpecificationsDraft({specs,onChange}){
  const [text,setText]=useState(()=>specs.map(([k,v])=>`${k}: ${v}`).join('\n'));
  return <textarea aria-label="Draft equipment specifications" rows={6} value={text} onChange={e=>{setText(e.target.value);onChange(e.target.value.split('\n').filter(line=>line.trim()).map(line=>{const i=line.indexOf(':');return i<0?[line,'']:[line.slice(0,i).trim(),line.slice(i+1).trim()];}));}}/>;
}
