import { useState } from 'react';
import { ArrowRight, Download, MapPin } from 'lucide-react';
import { setups, equipment, matchesSetup } from '../data/catalog.js';
import { PageHeading, FilterBar, SearchBox, Empty, Status, asset } from './UI.jsx';
import { downloadFile } from '../lib/storage.js';

export default function Setups({ state, update, onExplore }) {
  const [includePlanned,setIncludePlanned]=useState(true);
  const filtered=setups.filter(s=>matchesSetup(s,state) && (includePlanned || !['Planned','In development'].includes(s.status)));
  return <><PageHeading title="Available setups" action={<button className="button secondary" onClick={()=>downloadFile('cornerstone-setup-catalog.json',{version:1,asOf:'2026-09-30',setups,equipment})}><Download size={16}/>Export catalog</button>}>A directory of documented configurations, service capabilities and future upgrades.</PageHeading><FilterBar state={state} update={update} extra/><div className="library-toolbar"><SearchBox value={state.query} onChange={query=>update({query})} placeholder="Search a measurement, capability or lab…" label="Search setups"/><label className="checkbox-label"><input type="checkbox" checked={includePlanned} onChange={e=>setIncludePlanned(e.target.checked)}/>Include planned setups</label><span className="muted">{filtered.length} setups</span></div><div className="panel setup-directory"><div className="directory-table-header"><span>Measurement setup</span><span>Configuration</span><span>Location</span><span>Documentation status</span><span/></div>{filtered.map(s=><div className="directory-row" key={s.id}><div className="directory-name"><div className="directory-thumb">{s.photos.length?<img src={asset(s.photos[0])} alt=""/>:<span>◇</span>}</div><div><h3>{s.name}</h3><p>{s.subtitle}</p></div></div><div className="directory-config"><strong>{s.scale} · {s.mode}</strong><small>{s.bands.length?s.bands.join(' / '):'No optical band'}</small></div><span className="directory-lab">{s.lab}</span><Status value={s.status}/><button className="button ghost" aria-label={`Select ${s.name}`} onClick={()=>onExplore(s.id)}>Select<ArrowRight size={16}/></button></div>)}{!filtered.length && <Empty title="No setups found">Change the filters or try a different search term.</Empty>}</div><div className="catalog-note"><strong>What these statuses mean</strong><p>Documented = recorded in the supplied presentation. Service listed = described on the CORNERSTONE website. Needs verification = incomplete or conflicting configuration details. Planned and In development = work still to be completed. Status does not indicate booking or operational availability.</p></div></>;
}
