import { ArrowRight, Cpu, Camera, Zap, Monitor, Download } from 'lucide-react';
import { getEquipment } from '../data/catalog.js';
import { Inspector } from './SetupCanvas.jsx';
import { downloadFile } from '../lib/storage.js';

export default function SignalPath({ setup, selected, onSelect, onInspect }) {
  const electrical = setup.kind === 'electrical';
  const sourceId = setup.equipment.includes('laser')?'laser':'band-source';
  const detectorId = setup.equipment.includes('detector')?'detector':'band-detector';
  const deviceId = setup.scale === 'Wafer'?'wafer':'stage';
  const nodes = electrical ? [{id:'electrical',title:'Electrical drive',text:'Approved bias / current'},{id:deviceId,title:'Device under test',text:'Electrical probe contacts'},{id:'electrical',title:'Electrical readout',text:'Resistance / electrical response'}] : [{id:sourceId,title:'Optical source',text:setup.bands.join(' / ')},{id:'polarisation',title:'Polarisation control',text:'TE / TM configuration'},{id:'fibre',title:'Input coupling',text:setup.id==='chip-edge'?'Chip facet · proposed':'Fibre → grating coupler'},{id:deviceId,title:'Device under test',text:setup.scale==='Wafer'?'On-wafer device':'Photonic chip'},{id:'fibre',title:'Output coupling',text:'Device → collection fibre'},{id:detectorId,title:'Optical detector',text:'Transmission readout'}];
  const availableNodes = nodes.filter(n=>setup.equipment.includes(n.id));
  return <div className="tab-content signal-view"><div className="section-heading"><div><h3>Follow the signal</h3><p>{electrical?'Electrical stimulus → device → readout':'Optical source → coupling → device → detection'}</p></div><button className="button ghost" onClick={()=>downloadFile(`${setup.id}-signal-path.txt`, `${setup.name}\nSchematic connection sequence; confirm against approved SOP.\n\n${availableNodes.map((n,i)=>`${i+1}. ${n.title}: ${n.text}`).join('\n')}\n\nCamera: visual alignment only. Computer: control and acquisition.`, 'text/plain')}><Download size={15}/>Export</button></div><div className="signal-key"><span className={electrical?'line-key electrical':'line-key'}/>{electrical?'Electrical path':'Optical path'}<span className="line-key control"/>Control / observation</div><ol className={`signal-nodes ${electrical?'electrical':''}`}>{availableNodes.map((n,i)=><li key={`${n.id}-${i}`}><button aria-label={`Inspect path component: ${n.title}`} aria-pressed={selected===n.id} className={selected===n.id?'selected':''} onClick={()=>onSelect(n.id)}><span className="path-number">{i+1}</span><Cpu size={24}/><strong>{n.title}</strong><small>{n.text}</small></button>{i<availableNodes.length-1 && <ArrowRight className="path-arrow" size={18}/>}</li>)}</ol><div className="signal-support">{setup.kind==='electro-optic' && <button className="support-node" onClick={()=>onSelect('electrical')}><Zap size={22}/><span><strong>Electrical drive → DUT</strong><small>Bias / heater drive alongside the optical path</small></span></button>}<button className="support-node" onClick={()=>onSelect('camera')}><Camera size={22}/><span><strong>Camera → alignment display</strong><small>Observation, separate from the measured signal</small></span></button><div className="support-node"><Monitor size={22}/><span><strong>Computer → instruments</strong><small>Control, acquisition and data export</small></span></div></div><div className="note">Schematic connection sequence · Confirm ports, cables, trigger wiring and instrument configuration with the approved local procedure. {setup.status==='Planned'?'This setup is planned.':''}</div><Inspector id={selected} onInspect={onInspect}/></div>;
}
