import { lazy, Suspense, useMemo, useState } from 'react';
import { ArrowLeft, ArrowRight, Check, RotateCcw, Download, BookOpen } from 'lucide-react';
import { setups, guideSteps } from '../data/catalog.js';
import { workspaceSeed, draftStorageKey, contentSignature, validateWorkspace } from '../lib/workspace_draft.js';
import { readLocal, writeLocal, downloadFile } from '../lib/storage.js';
import { nodeName } from './Graph_draft.jsx';
import '../workspaces_draft.css';
const ModelScene=lazy(()=>import('./ModelScene.jsx'));
const stepFocus=[['mainframe','dut'],['laser','controller','sensor'],['dut','input-arm','output-arm','camera'],['controller','laser','sensor'],['laser','sensor'],['dut','sensor']];
export default function Training_draft({setupId='wst-optical-manual',onSetupChange,onBench,onInspect}){
  const [source,setSource]=useState('published');
  const draft=useMemo(()=>{const seed=workspaceSeed(setupId);if(source==='draft')try{return validateWorkspace(readLocal(draftStorageKey(setupId),seed));}catch{}return seed;},[setupId,source]);
  const entry=setups.find(s=>s.id===setupId),steps=draft.procedure?.length?draft.procedure:(guideSteps[entry?.guide]||[]).map(([title,text])=>({title,text}));
  const fingerprint=contentSignature({id:draft.id,procedure:steps});
  const saved=readLocal(`training_draft:${setupId}:${source}`,{});
  const [progress,setProgress]=useState(()=>saved.fingerprint===fingerprint?saved.done||[]:[]),[step,setStep]=useState(0),[notes,setNotes]=useState(()=>saved.fingerprint===fingerprint?saved.notes||'':''),[notice,setNotice]=useState('');
  const active=steps[step],focusIds=stepFocus[step]?.filter(id=>draft.nodes.some(n=>n.id===id))||[],related=focusIds.length?draft.nodes.filter(n=>focusIds.includes(n.id)):draft.nodes.slice(0,4);
  const focus=useMemo(()=>related[0]?{id:related[0].id}:undefined,[related[0]?.id]);
  function save(done,note=notes){const data={workspaceName:'Training_draft',version:1,setupId,source,fingerprint,done,notes:note,updatedAt:new Date().toISOString()};setProgress(done);setNotice(writeLocal(`training_draft:${setupId}:${source}`,data)?'Training progress saved in this browser.':'Browser storage unavailable; export your session.');}
  function switchSource(value){
    let next=workspaceSeed(setupId);if(value==='draft')try{next=validateWorkspace(readLocal(draftStorageKey(setupId),next));}catch{}
    const nextSteps=next.procedure?.length?next.procedure:(guideSteps[entry?.guide]||[]).map(([title,text])=>({title,text}));
    const nextFingerprint=contentSignature({id:next.id,procedure:nextSteps}),data=readLocal(`training_draft:${setupId}:${value}`,{}),matches=data.fingerprint===nextFingerprint;
    setSource(value);setStep(0);setProgress(matches&&Array.isArray(data.done)?data.done:[]);setNotes(matches&&typeof data.notes==='string'?data.notes:'');setNotice(matches?'Saved training progress restored for this guide.':'Guide changed. Start a new checklist for this version.');
  }
  return <div className="draft-workspace"><div className="draft-heading"><div><span className="draft-eyebrow">CORNERSTONE / GUIDED MEASUREMENT</span><h1>Training<span>_draft</span></h1><p>One step at a time, with the equipment beside your instructions.</p></div><button className="button secondary" onClick={onBench}>Open Bench_draft<ArrowRight size={15}/></button></div>
    <div className="draft-training-context panel"><label>Setup<select aria-label="Training draft setup" value={setupId} onChange={e=>onSetupChange(e.target.value)}>{setups.map(s=><option key={s.id} value={s.id}>{s.name}</option>)}</select></label><label>Guide version<select aria-label="Training guide source" value={source} onChange={e=>switchSource(e.target.value)}><option value="published">Published / catalog guide</option><option value="draft">Bench_draft guide</option></select></label><span>{progress.length} / {steps.length} steps reviewed</span><button className="text-button" onClick={()=>{save([], '');setNotes('');setStep(0);}}><RotateCcw size={14}/>Reset session</button></div>
    <div className="draft-training-note"><BookOpen size={18}/><span>Training checklist · follow the approved local SOP and instrument training. Reviewing a step does not operate the hardware.</span></div>{notice&&<div className="draft-notice" role="status">{notice}</div>}
    <div className="draft-training-layout"><nav className="draft-step-list panel" aria-label="Measurement steps">{steps.map((s,i)=><button key={i} aria-current={step===i?'step':undefined} onClick={()=>setStep(i)}><span className={progress.includes(i)?'done':''}>{progress.includes(i)?<Check size={15}/>:String(i+1).padStart(2,'0')}</span><strong>{s.title}</strong></button>)}<div className="draft-training-progress"><span style={{width:`${steps.length?progress.length/steps.length*100:0}%`}}/></div></nav>
    <section className="draft-training-step panel">{active?<><div className="draft-step-title"><span>STEP {String(step+1).padStart(2,'0')} / {steps.length}</span><h2>{active.title}</h2><p>{active.text}</p></div><div className="draft-training-scene"><Suspense fallback={<div className="draft-loading model-loading">Loading related equipment…</div>}><ModelScene nodes={draft.nodes} connections={draft.connections} focusRequest={focus} highlightedNodeIds={related.map(n=>n.id)} onSelect={id=>{const n=draft.nodes.find(n=>n.id===id);if(n)onInspect(n.equipmentId);}}/></Suspense></div><div className="draft-training-equipment">{related.map(n=><button key={n.id} onClick={()=>onInspect(n.equipmentId)}>{nodeName(n)}<ArrowRight size={13}/></button>)}</div><div className="draft-step-actions"><button className="button secondary" disabled={step===0} onClick={()=>setStep(v=>v-1)}><ArrowLeft size={14}/>Previous</button><button className="button primary" aria-pressed={progress.includes(step)} onClick={()=>save(progress.includes(step)?progress.filter(i=>i!==step):[...progress,step])}><Check size={15}/>{progress.includes(step)?'Reviewed · unmark':'Mark reviewed'}</button><button className="button secondary" disabled={step===steps.length-1} onClick={()=>setStep(v=>v+1)}>Next<ArrowRight size={14}/></button></div></>:<div className="draft-empty">No guide steps are recorded for this setup. Add them in Bench_draft.</div>}</section></div>
    <section className="draft-session-notes panel"><label>Session notes<textarea rows={3} placeholder="Observations, questions and handover notes…" value={notes} onChange={e=>{setNotes(e.target.value);save(progress,e.target.value);}}/></label><button className="button secondary" onClick={()=>downloadFile(`${setupId}-training_draft.json`,{version:1,workspaceName:'Training_draft',setupId,source,fingerprint,done:progress,notes,steps})}><Download size={15}/>Export training session</button></section>
  </div>;
}
